### ISSUE TITLE
Entrepreneurship report: feedback from Open Data team

### ISSUE THREAD

**Issue by asRodelgo** [asRodelgo/reportGenerator360#5]
- Some footnote source links are broken. Double check URLs
- Some units are not clear for some indicators. Ex: Policy 1-7 (best) change to "1 - 7=best"
- Barcharts, colors differ slightly between legend and bars themselves (lighter on bars)

**Comment by mrpsonglao** [comment]
Addressed by pull request #7 

See attached PDF for sample Entrepreneurship report with these issues fixed.
[Entrepreneurship_USA.pdf](https://github.com/asRodelgo/reportGenerator360/files/1235574/Entrepreneurship_USA.pdf)

*1. Some footnote source links are broken. Double check URLs*
- **Cause:** Section_Description (in Entrepreneurship_ReportConfiguration.csv) and Source_Name (in Entrepreneurship_DataDescription.csv) didn't match. As a result, left-joining these dataframes via datapull_TCdata360.R code wasn't successful.
- **Solution:** Revised the latter to match the previous.

*2. Some units are not clear for some indicators. Ex: Policy 1-7 (best) change to "1 - 7=best"*
- **Solution:** Fixed the Unit_Short column in the Entrepreneurship_DataDescription.csv file to fix units (esp. those with "best" or fixed some misspelled words)

*3. Barcharts, colors differ slightly between legend and bars themselves (lighter on bars)*
- **Cause:** Plot for bar_facewrap_chart has ggplot attribute scale_alpha_manual(labels = order_legend,values = c(1, rep(0.4,4)),guide=FALSE), which causes the bar plot fill to have alpha = 0.4 whereas the legend has alpha = 1.0
- **Solution:** Edited helper_functions.R. Replaced barplot fill alpha to rep(1,4) so that alpha=1.0 for bar plot matches alpha=1.0 for legend.
